# Generated by Django 3.1.6 on 2021-04-04 10:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210330_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(default=accounts.models.get_expiry, null=True),
        ),
    ]
